### ISSUE TITLE
Consider moving the Wiki content into .md files in the project

### ISSUE THREAD

**Issue by marcpage** [mefistotelis/pylabview#13]
I have several updates to the Wiki content (specifically Version info related to my two pull requests) but some other general fix ups. If these we .md files in the project, I could just submit pull requests. GitHub does not have a good workflow for submitting updates to wiki pages. 

Plus this information is super helpful to have at-hand when you clone the repo.

**Comment by mefistotelis** [comment]
Done. Wiki is now generated from source repo.
