### ISSUE TITLE
How did you derive the heap tag enums?

### ISSUE THREAD

**Issue by rcpacini** [mefistotelis/pylabview#19]
Thanks for laying the groundwork for a python interpreter for LabVIEW files.

How did you derive the heap tag enum names and ids in `LVHeap.py`?

(i.e. System Level (SL_), and Object Fields (OF_) tags).

Were these tags exported from LabVIEW via Invoke, Property, or DLL Functional calls?

**Comment by mefistotelis** [comment]
Names of tags were used for best compatibility with LabVIEW formats.
I used the LabVIEW [heap peek debug tool](https://labviewwiki.org/wiki/Heap_Peek) to export few heaps to XML, then found more complete lists of the tags by looking at labview binary code.

**Comment by rcpacini** [comment]
What method did you use to export to XML? Thanks again for your help.

**Comment by mefistotelis** [comment]
> What method did you use to export to XML?

If I remeber correctly, the XML option was a part of Heap Peek.

**Comment by rcpacini** [comment]
Yes it is.  

Instructions:
1. Add "LVdebugKeys=True" to LabVIEW.ini to enable Ned & Heap Peek.
2. Restart LabVIEW and open a VI
4. Start Heap Peek "Ned" by (Ctrl+Shift+D+N)
5. Under "Heap Save Format", click to cycle to 'XML'
6. Save the VI
7. Read the resource file (.vi) block 'BDHX' or 'FPHX'

All my questions are answered. I appreciate the help.
